name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi
          python -m pip install --upgrade ruff black pytest pytest-cov

      - name: Lint (ruff)
        run: python -m ruff check .

      - name: Format (black --check)
        run: python -m black --check .

      - name: Run tests with coverage (pytest.ini controls thresholds)
        env:
          PYTHONWARNINGS: ignore
        run: python -m pytest -q
