name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Show environment
        run: |
          python -V
          pip -V
          uname -a

      - name: Install deps (prod + dev)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest-cov

      - name: Lint (ruff)
        run: ruff check .

      - name: Format (black --check)
        run: black --check .

      - name: Run tests with coverage (uses pytest.ini)
        env:
          PYTHONWARNINGS: ignore
        run: pytest -q

      - name: If failed, print tree and config
        if: failure()
        run: |
          echo "::group::Project tree"
          ls -la
          echo "::endgroup::"
          echo "::group::Show pytest.ini / .coveragerc / requirements"
          [ -f pytest.ini ] && sed -n '1,200p' pytest.ini || true
          [ -f .coveragerc ] && sed -n '1,200p' .coveragerc || true
          [ -f requirements.txt ] && sed -n '1,200p' requirements.txt || true
          [ -f requirements-dev.txt ] && sed -n '1,200p' requirements-dev.txt || true
          echo "::endgroup::"
