name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # app/runtime deps (already have a requirements.txt)
          pip install -r requirements.txt || true
          # dev/test deps
          pip install -r requirements-dev.txt
          # coverage plugin (already installed locally, install here too)
          pip install pytest-cov

      - name: Lint (Ruff)
        run: ruff check .

      - name: Format check (Black)
        run: black --check .

      - name: Tests + Coverage
        # pytest.ini already sets --cov and --cov-fail-under
        run: pytest -q

      - name: Upload coverage report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-raw
          path: ./.coverage
          if-no-files-found: ignore
