- name: Install deps (prod + dev)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi
          # Ensure CLIs are present even if requirements-dev.txt is missing
          python -m pip install --upgrade ruff black pytest pytest-cov

      - name: Lint (ruff)
        run: python -m ruff check .

      - name: Format (black --check)
        run: python -m black --check .

      - name: Run tests with coverage (uses pytest.ini)
        env:
          PYTHONWARNINGS: ignore
        run: python -m pytest -q
