name: Data Pipeline

on:
  workflow_dispatch:            # run manually from the Actions tab
  push:
    paths:
      - "src/**"
      - "Makefile"
      - "requirements.txt"
  schedule:
    # Runs daily at 11:00 UTC (07:00 in Toronto while on EDT; 06:00 after Nov time change)
    - cron: "0 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run full pipeline
        run: |
          make all

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            reports/**/*.png
            reports/**/*.md
          if-no-files-found: warn

      - name: Upload processed/cleaned data
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: |
            data/processed/**
            data/cleaned/**
          if-no-files-found: warn

      - name: Upload SQLite warehouse
        uses: actions/upload-artifact@v4
        with:
          name: warehouse
          path: data/warehouse.db
          if-no-files-found: warn
